/* WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM A .SM FILE.
 * Changes made here will certainly be overwritten.
 */

/* 
 * (C) 2001 Clemson University and The University of Chicago 
 *
 * See COPYING in top-level directory.
 */

#include <string.h>
#include <assert.h>

#include "server-config.h"
#include "pvfs2-server.h"
#include "pvfs2-attr.h"
#include "pvfs2-util.h"
#include "pvfs2-internal.h"
#include "pint-util.h"

PVFS_ds_attributes set_df_attr;

static struct PINT_state_s ST_prelude;
static struct PINT_pjmp_tbl_s ST_prelude_pjtbl[];
static struct PINT_tran_tbl_s ST_prelude_trtbl[];

static PINT_sm_action get_datafile_attribs_op(
	struct PINT_smcb *smcb, job_status_s *js_p);

static struct PINT_state_s ST_get_datafile_attribs;
static struct PINT_pjmp_tbl_s ST_get_datafile_attribs_pjtbl[];
static struct PINT_tran_tbl_s ST_get_datafile_attribs_trtbl[];

static PINT_sm_action set_datafile_attribs_op(
	struct PINT_smcb *smcb, job_status_s *js_p);

static struct PINT_state_s ST_set_datafile_attribs;
static struct PINT_pjmp_tbl_s ST_set_datafile_attribs_pjtbl[];
static struct PINT_tran_tbl_s ST_set_datafile_attribs_trtbl[];

static PINT_sm_action set_response_value_op(
	struct PINT_smcb *smcb, job_status_s *js_p);

static struct PINT_state_s ST_set_response_value;
static struct PINT_pjmp_tbl_s ST_set_response_value_pjtbl[];
static struct PINT_tran_tbl_s ST_set_response_value_trtbl[];
static struct PINT_state_s ST_final_response;
static struct PINT_pjmp_tbl_s ST_final_response_pjtbl[];
static struct PINT_tran_tbl_s ST_final_response_trtbl[];

static PINT_sm_action setattr_cleanup(
	struct PINT_smcb *smcb, job_status_s *js_p);

static struct PINT_state_s ST_cleanup;
static struct PINT_pjmp_tbl_s ST_cleanup_pjtbl[];
static struct PINT_tran_tbl_s ST_cleanup_trtbl[];

struct PINT_state_machine_s pvfs2_set_df_attr_server_sm = {
	.name = "pvfs2_set_df_attr_server_sm",
	.first_state = &ST_prelude
};

static struct PINT_state_s ST_prelude = {
	 .state_name = "prelude" ,
	 .parent_machine = &pvfs2_set_df_attr_server_sm ,
	 .flag = SM_JUMP ,
	 .action.nested = &pvfs2_prelude_sm ,
	 .pjtbl = NULL ,
	 .trtbl = ST_prelude_trtbl 
};

static struct PINT_tran_tbl_s ST_prelude_trtbl[] = {
	{ .return_value = 0 ,
	 .next_state = &ST_get_datafile_attribs },
	{ .return_value = -1 ,
	 .next_state = &ST_final_response }
};

static struct PINT_state_s ST_get_datafile_attribs = {
	 .state_name = "get_datafile_attribs" ,
	 .parent_machine = &pvfs2_set_df_attr_server_sm ,
	 .flag = SM_RUN ,
	 .action.func = get_datafile_attribs_op ,
	 .pjtbl = NULL ,
	 .trtbl = ST_get_datafile_attribs_trtbl 
};

static struct PINT_tran_tbl_s ST_get_datafile_attribs_trtbl[] = {
	{ .return_value = 0 ,
	 .next_state = &ST_set_datafile_attribs },
	{ .return_value = -1 ,
	 .next_state = &ST_final_response }
};

static struct PINT_state_s ST_set_datafile_attribs = {
	 .state_name = "set_datafile_attribs" ,
	 .parent_machine = &pvfs2_set_df_attr_server_sm ,
	 .flag = SM_RUN ,
	 .action.func = set_datafile_attribs_op ,
	 .pjtbl = NULL ,
	 .trtbl = ST_set_datafile_attribs_trtbl 
};

static struct PINT_tran_tbl_s ST_set_datafile_attribs_trtbl[] = {
	{ .return_value = 0 ,
	 .next_state = &ST_set_response_value },
	{ .return_value = -1 ,
	 .next_state = &ST_final_response }
};

static struct PINT_state_s ST_set_response_value = {
	 .state_name = "set_response_value" ,
	 .parent_machine = &pvfs2_set_df_attr_server_sm ,
	 .flag = SM_RUN ,
	 .action.func = set_response_value_op ,
	 .pjtbl = NULL ,
	 .trtbl = ST_set_response_value_trtbl 
};

static struct PINT_tran_tbl_s ST_set_response_value_trtbl[] = {
	{ .return_value = -1 ,
	 .next_state = &ST_final_response }
};

static struct PINT_state_s ST_final_response = {
	 .state_name = "final_response" ,
	 .parent_machine = &pvfs2_set_df_attr_server_sm ,
	 .flag = SM_JUMP ,
	 .action.nested = &pvfs2_final_response_sm ,
	 .pjtbl = NULL ,
	 .trtbl = ST_final_response_trtbl 
};

static struct PINT_tran_tbl_s ST_final_response_trtbl[] = {
	{ .return_value = -1 ,
	 .next_state = &ST_cleanup }
};

static struct PINT_state_s ST_cleanup = {
	 .state_name = "cleanup" ,
	 .parent_machine = &pvfs2_set_df_attr_server_sm ,
	 .flag = SM_RUN ,
	 .action.func = setattr_cleanup ,
	 .pjtbl = NULL ,
	 .trtbl = ST_cleanup_trtbl 
};

static struct PINT_tran_tbl_s ST_cleanup_trtbl[] = {
	{ .return_value = -1 ,

	 .flag = SM_TERM }
};

# 62 "src/server/set-datafile-sttr-server.sm"


/* Get the origianl datafile's attributes */
static PINT_sm_action get_datafile_attribs_op(struct PINT_smcb *smcb, job_status_s *js_p)
{


  
  job_id_t j_id;
  struct PINT_server_op *s_op = PINT_sm_frame(smcb, PINT_FRAME_CURRENT);
  
  //  gossip_debug(GOSSIP_LB_DEBUG, "\n\n Get the request \n\n");
  return (job_trove_dspace_getattr(
				   s_op->req->u.set_df_attr_poster.fs_id,
				   s_op->req->u.set_df_attr_poster.handle,
				   smcb,
				   &set_df_attr,
				   0,
				   js_p,
				   &j_id,
				   server_job_context,
				   NULL)
	  );
}


/* /\* Get the origianl datafile's attributes *\/ */
/* static PINT_sm_action check_datafile_attribs_op(struct PINT_smcb *smcb, job_status_s *js_p) */
/* { */


  
/*   job_id_t j_id; */
/*   struct PINT_server_op *s_op = PINT_sm_frame(smcb, PINT_FRAME_CURRENT); */
  
/*   memset(&set_df_attr, 0, sizeof(set_df_attr)); */

/*   //  gossip_debug(GOSSIP_LB_DEBUG, "\n\n Get the request \n\n"); */
/*   return (job_trove_dspace_getattr( */
/* 				   s_op->req->u.set_df_attr_poster.fs_id, */
/* 				   s_op->req->u.set_df_attr_poster.handle, */
/* 				   smcb, */
/* 				   &set_df_attr, */
/* 				   0, */
/* 				   js_p, */
/* 				   &j_id, */
/* 				   server_job_context, */
/* 				   NULL) */
/* 	  ); */
/* } */


/* Add metafile to datafile's attributes */
static PINT_sm_action set_datafile_attribs_op(struct PINT_smcb *smcb, job_status_s *js_p)
{

  int ret;
  struct PINT_server_op *s_op = PINT_sm_frame(smcb, PINT_FRAME_CURRENT);
  job_id_t j_id;

 
  set_df_attr.metafile = s_op->req->u.set_df_attr_poster.metafile;

  ret = job_trove_dspace_setattr(
        s_op->req->u.set_df_attr_poster.fs_id, 
	s_op->req->u.set_df_attr_poster.handle,
        &set_df_attr, 
        TROVE_SYNC,
        smcb, 
	0, 
	js_p, 
	&j_id, 
	server_job_context, 
	NULL);
  
  return ret;  
  
}



/* Set response value to 0, indicating all is OK */
static PINT_sm_action  set_response_value_op(struct PINT_smcb *smcb, job_status_s *js_p){
  struct PINT_server_op *s_op = PINT_sm_frame(smcb, PINT_FRAME_CURRENT);

//  gossip_debug(GOSSIP_LB_DEBUG, "Set df attr finished for %lld with metafile %lld\n",s_op->req->u.set_df_attr_poster.handle, set_df_attr.metafile);

  s_op->resp.u.set_df_attr_poster.handle = 2;

  js_p->error_code = 0;
  return SM_ACTION_COMPLETE;
}

static PINT_sm_action setattr_cleanup(struct PINT_smcb *smcb, job_status_s *js_p){
  js_p->error_code = 0;
  return (server_state_machine_complete(smcb));

}


PINT_GET_OBJECT_REF_DEFINE(set_df_attr_poster);

struct PINT_server_req_params pvfs2_set_datafile_attr_server_params =
{
    .string_name = "set_df_attr",
    .perm = PINT_SERVER_CHECK_NONE,
    .access_type = PINT_server_req_modify,
    .sched_policy = PINT_SERVER_REQ_SCHEDULE,
    .get_object_ref = PINT_get_object_ref_set_df_attr_poster,
    .state_machine = &pvfs2_set_df_attr_server_sm
};

/*
 * Local variables:
 *  mode: c
 *  c-indent-level: 4
 *  c-basic-offset: 4
 * End:
 *
 * vim: ft=c ts=8 sts=4 sw=4 expandtab
 */

